import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-vercel-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   ALTER TYPE "public"."enum_pages_hero_links_link_type" ADD VALUE 'none';
  ALTER TYPE "public"."enum_pages_blocks_cta_links_link_type" ADD VALUE 'none';
  ALTER TYPE "public"."enum_pages_blocks_button_link_type" ADD VALUE 'none';
  ALTER TYPE "public"."enum_pages_blocks_content_columns_link_type" ADD VALUE 'none';
  ALTER TYPE "public"."enum_pages_blocks_our_service_services_link_type" ADD VALUE 'none';
  ALTER TYPE "public"."enum_pages_blocks_tools_we_support_link_type" ADD VALUE 'none';
  ALTER TYPE "public"."enum_pages_blocks_who_we_are_items_link_type" ADD VALUE 'none';
  ALTER TYPE "public"."enum_pages_blocks_projects_overview_units_button_link_type" ADD VALUE 'none';
  ALTER TYPE "public"."enum__pages_v_version_hero_links_link_type" ADD VALUE 'none';
  ALTER TYPE "public"."enum__pages_v_blocks_cta_links_link_type" ADD VALUE 'none';
  ALTER TYPE "public"."enum__pages_v_blocks_button_link_type" ADD VALUE 'none';
  ALTER TYPE "public"."enum__pages_v_blocks_content_columns_link_type" ADD VALUE 'none';
  ALTER TYPE "public"."enum__pages_v_blocks_our_service_services_link_type" ADD VALUE 'none';
  ALTER TYPE "public"."enum__pages_v_blocks_tools_we_support_link_type" ADD VALUE 'none';
  ALTER TYPE "public"."enum__pages_v_blocks_who_we_are_items_link_type" ADD VALUE 'none';
  ALTER TYPE "public"."enum__pages_v_blocks_projects_overview_units_button_link_type" ADD VALUE 'none';
  ALTER TYPE "public"."enum_header_nav_items_link_type" ADD VALUE 'none';
  ALTER TYPE "public"."enum_footer_nav_items_link_type" ADD VALUE 'none';
  ALTER TYPE "public"."enum_footer_about_us_link_actions_link_type" ADD VALUE 'none';
  ALTER TYPE "public"."enum_footer_contact_us_link_actions_link_type" ADD VALUE 'none';
  ALTER TABLE "header_nav_items_link_sublinks" ALTER COLUMN "label" DROP NOT NULL;
  ALTER TABLE "footer_nav_items_link_sublinks" ALTER COLUMN "label" DROP NOT NULL;
  ALTER TABLE "footer_about_us_link_actions_link_sublinks" ALTER COLUMN "label" DROP NOT NULL;
  ALTER TABLE "footer_contact_us_link_actions_link_sublinks" ALTER COLUMN "label" DROP NOT NULL;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_hero_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "pages_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_pages_hero_links_link_type";
  CREATE TYPE "public"."enum_pages_hero_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "pages_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_pages_hero_links_link_type";
  ALTER TABLE "pages_hero_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_pages_hero_links_link_type" USING "link_type"::"public"."enum_pages_hero_links_link_type";
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_pages_blocks_cta_links_link_type";
  CREATE TYPE "public"."enum_pages_blocks_cta_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_pages_blocks_cta_links_link_type";
  ALTER TABLE "pages_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_pages_blocks_cta_links_link_type" USING "link_type"::"public"."enum_pages_blocks_cta_links_link_type";
  ALTER TABLE "pages_blocks_button" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_button" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_pages_blocks_button_link_type";
  CREATE TYPE "public"."enum_pages_blocks_button_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "pages_blocks_button" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_pages_blocks_button_link_type";
  ALTER TABLE "pages_blocks_button" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_pages_blocks_button_link_type" USING "link_type"::"public"."enum_pages_blocks_button_link_type";
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_pages_blocks_content_columns_link_type";
  CREATE TYPE "public"."enum_pages_blocks_content_columns_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_pages_blocks_content_columns_link_type";
  ALTER TABLE "pages_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_pages_blocks_content_columns_link_type" USING "link_type"::"public"."enum_pages_blocks_content_columns_link_type";
  ALTER TABLE "pages_blocks_our_service_services" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_our_service_services" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_pages_blocks_our_service_services_link_type";
  CREATE TYPE "public"."enum_pages_blocks_our_service_services_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "pages_blocks_our_service_services" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_pages_blocks_our_service_services_link_type";
  ALTER TABLE "pages_blocks_our_service_services" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_pages_blocks_our_service_services_link_type" USING "link_type"::"public"."enum_pages_blocks_our_service_services_link_type";
  ALTER TABLE "pages_blocks_tools_we_support" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_tools_we_support" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_pages_blocks_tools_we_support_link_type";
  CREATE TYPE "public"."enum_pages_blocks_tools_we_support_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "pages_blocks_tools_we_support" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_pages_blocks_tools_we_support_link_type";
  ALTER TABLE "pages_blocks_tools_we_support" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_pages_blocks_tools_we_support_link_type" USING "link_type"::"public"."enum_pages_blocks_tools_we_support_link_type";
  ALTER TABLE "pages_blocks_who_we_are_items" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_who_we_are_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_pages_blocks_who_we_are_items_link_type";
  CREATE TYPE "public"."enum_pages_blocks_who_we_are_items_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "pages_blocks_who_we_are_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_pages_blocks_who_we_are_items_link_type";
  ALTER TABLE "pages_blocks_who_we_are_items" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_pages_blocks_who_we_are_items_link_type" USING "link_type"::"public"."enum_pages_blocks_who_we_are_items_link_type";
  ALTER TABLE "pages_blocks_projects_overview" ALTER COLUMN "units_button_link_type" SET DATA TYPE text;
  ALTER TABLE "pages_blocks_projects_overview" ALTER COLUMN "units_button_link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_pages_blocks_projects_overview_units_button_link_type";
  CREATE TYPE "public"."enum_pages_blocks_projects_overview_units_button_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "pages_blocks_projects_overview" ALTER COLUMN "units_button_link_type" SET DEFAULT 'reference'::"public"."enum_pages_blocks_projects_overview_units_button_link_type";
  ALTER TABLE "pages_blocks_projects_overview" ALTER COLUMN "units_button_link_type" SET DATA TYPE "public"."enum_pages_blocks_projects_overview_units_button_link_type" USING "units_button_link_type"::"public"."enum_pages_blocks_projects_overview_units_button_link_type";
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__pages_v_version_hero_links_link_type";
  CREATE TYPE "public"."enum__pages_v_version_hero_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__pages_v_version_hero_links_link_type";
  ALTER TABLE "_pages_v_version_hero_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__pages_v_version_hero_links_link_type" USING "link_type"::"public"."enum__pages_v_version_hero_links_link_type";
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__pages_v_blocks_cta_links_link_type";
  CREATE TYPE "public"."enum__pages_v_blocks_cta_links_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__pages_v_blocks_cta_links_link_type";
  ALTER TABLE "_pages_v_blocks_cta_links" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__pages_v_blocks_cta_links_link_type" USING "link_type"::"public"."enum__pages_v_blocks_cta_links_link_type";
  ALTER TABLE "_pages_v_blocks_button" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_button" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__pages_v_blocks_button_link_type";
  CREATE TYPE "public"."enum__pages_v_blocks_button_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_pages_v_blocks_button" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__pages_v_blocks_button_link_type";
  ALTER TABLE "_pages_v_blocks_button" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__pages_v_blocks_button_link_type" USING "link_type"::"public"."enum__pages_v_blocks_button_link_type";
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__pages_v_blocks_content_columns_link_type";
  CREATE TYPE "public"."enum__pages_v_blocks_content_columns_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__pages_v_blocks_content_columns_link_type";
  ALTER TABLE "_pages_v_blocks_content_columns" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__pages_v_blocks_content_columns_link_type" USING "link_type"::"public"."enum__pages_v_blocks_content_columns_link_type";
  ALTER TABLE "_pages_v_blocks_our_service_services" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_our_service_services" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__pages_v_blocks_our_service_services_link_type";
  CREATE TYPE "public"."enum__pages_v_blocks_our_service_services_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_pages_v_blocks_our_service_services" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__pages_v_blocks_our_service_services_link_type";
  ALTER TABLE "_pages_v_blocks_our_service_services" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__pages_v_blocks_our_service_services_link_type" USING "link_type"::"public"."enum__pages_v_blocks_our_service_services_link_type";
  ALTER TABLE "_pages_v_blocks_tools_we_support" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_tools_we_support" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__pages_v_blocks_tools_we_support_link_type";
  CREATE TYPE "public"."enum__pages_v_blocks_tools_we_support_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_pages_v_blocks_tools_we_support" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__pages_v_blocks_tools_we_support_link_type";
  ALTER TABLE "_pages_v_blocks_tools_we_support" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__pages_v_blocks_tools_we_support_link_type" USING "link_type"::"public"."enum__pages_v_blocks_tools_we_support_link_type";
  ALTER TABLE "_pages_v_blocks_who_we_are_items" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_who_we_are_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__pages_v_blocks_who_we_are_items_link_type";
  CREATE TYPE "public"."enum__pages_v_blocks_who_we_are_items_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_pages_v_blocks_who_we_are_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum__pages_v_blocks_who_we_are_items_link_type";
  ALTER TABLE "_pages_v_blocks_who_we_are_items" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum__pages_v_blocks_who_we_are_items_link_type" USING "link_type"::"public"."enum__pages_v_blocks_who_we_are_items_link_type";
  ALTER TABLE "_pages_v_blocks_projects_overview" ALTER COLUMN "units_button_link_type" SET DATA TYPE text;
  ALTER TABLE "_pages_v_blocks_projects_overview" ALTER COLUMN "units_button_link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum__pages_v_blocks_projects_overview_units_button_link_type";
  CREATE TYPE "public"."enum__pages_v_blocks_projects_overview_units_button_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "_pages_v_blocks_projects_overview" ALTER COLUMN "units_button_link_type" SET DEFAULT 'reference'::"public"."enum__pages_v_blocks_projects_overview_units_button_link_type";
  ALTER TABLE "_pages_v_blocks_projects_overview" ALTER COLUMN "units_button_link_type" SET DATA TYPE "public"."enum__pages_v_blocks_projects_overview_units_button_link_type" USING "units_button_link_type"::"public"."enum__pages_v_blocks_projects_overview_units_button_link_type";
  ALTER TABLE "header_nav_items" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "header_nav_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_header_nav_items_link_type";
  CREATE TYPE "public"."enum_header_nav_items_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "header_nav_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_header_nav_items_link_type";
  ALTER TABLE "header_nav_items" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_header_nav_items_link_type" USING "link_type"::"public"."enum_header_nav_items_link_type";
  ALTER TABLE "footer_nav_items" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "footer_nav_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_footer_nav_items_link_type";
  CREATE TYPE "public"."enum_footer_nav_items_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "footer_nav_items" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_footer_nav_items_link_type";
  ALTER TABLE "footer_nav_items" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_footer_nav_items_link_type" USING "link_type"::"public"."enum_footer_nav_items_link_type";
  ALTER TABLE "footer_about_us_link_actions" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "footer_about_us_link_actions" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_footer_about_us_link_actions_link_type";
  CREATE TYPE "public"."enum_footer_about_us_link_actions_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "footer_about_us_link_actions" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_footer_about_us_link_actions_link_type";
  ALTER TABLE "footer_about_us_link_actions" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_footer_about_us_link_actions_link_type" USING "link_type"::"public"."enum_footer_about_us_link_actions_link_type";
  ALTER TABLE "footer_contact_us_link_actions" ALTER COLUMN "link_type" SET DATA TYPE text;
  ALTER TABLE "footer_contact_us_link_actions" ALTER COLUMN "link_type" SET DEFAULT 'reference'::text;
  DROP TYPE "public"."enum_footer_contact_us_link_actions_link_type";
  CREATE TYPE "public"."enum_footer_contact_us_link_actions_link_type" AS ENUM('reference', 'custom');
  ALTER TABLE "footer_contact_us_link_actions" ALTER COLUMN "link_type" SET DEFAULT 'reference'::"public"."enum_footer_contact_us_link_actions_link_type";
  ALTER TABLE "footer_contact_us_link_actions" ALTER COLUMN "link_type" SET DATA TYPE "public"."enum_footer_contact_us_link_actions_link_type" USING "link_type"::"public"."enum_footer_contact_us_link_actions_link_type";
  ALTER TABLE "header_nav_items_link_sublinks" ALTER COLUMN "label" SET NOT NULL;
  ALTER TABLE "footer_nav_items_link_sublinks" ALTER COLUMN "label" SET NOT NULL;
  ALTER TABLE "footer_about_us_link_actions_link_sublinks" ALTER COLUMN "label" SET NOT NULL;
  ALTER TABLE "footer_contact_us_link_actions_link_sublinks" ALTER COLUMN "label" SET NOT NULL;`)
}
